### PR TITLE
Ensure we handle escape characters when processing strings/regexes.

### LINKED ISSUE #84: Does not work with escaped characters inside regexes
With this file : 

```
"foo".replace(/[a-z\/]/g, "")
```
Gives the following error : 

```
~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/node_modules/magic-string/dist/magic-string.cjs.js:425
                                throw new Error('Cannot insert at replaced character index: ' + index);
                                      ^
Error: Cannot insert at replaced character index: 23
    at MagicString.insert (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/node_modules/magic-string/dist/magic-string.cjs.js:425:11)
    at patchSemicolons (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:1947:15)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:4921:5
    at traverse (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:473:23)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:464:11
    at Array.forEach (native)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:462:15
    at Array.forEach (native)
    at descend (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:459:32)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:4908:5
```

### PR DESCRIPTION
**Pull request by eventualbuddha**
Mostly this ensures we insert semicolons (or newlines etc) at the right positions, essentially anywhere we would try to trim the node range.

Closes #84.

cc @jeffchan @alexgorbatchev

### CODE REVIEW

File: test/utils/trimmedNodeRange_test.js [hunk 1]
```diff
@@ -50,4 +50,13 @@ describe('trimmedNodeRange', function() {
     const nodeRange = trimmedNodeRange(callNode, source);
     deepEqual(nodeRange, [0, 15]);
   });
+
+  it('does not eat into escaped regexes', () => {
+    const source = '"foo".replace(/[a-z\\/]/g, "")';
+    const ast = parse(source);
+    const regexNode = ast.body.statements[0].arguments[0];
+    debugger;
```
Comment (jeffchan) [inline test/utils/trimmedNodeRange_test.js]: Remove :)

**Comment by jeffchan** [comment]
thanks for fixing

File: test/utils/trimmedNodeRange_test.js (hunk 1 above)
Comment (eventualbuddha) [inline test/utils/trimmedNodeRange_test.js]: Hah, oops.
